top-page:

inquire-list-begin:

inquire-list-confirm:

inquire-list-user:

inquire-list-edit-user:

inquire-list-user-login:

inquire-list-user-register:

inquire-list-done:

inquire-list-delete-item:

request-point-begin:

request-point-confirm:

request-point-done:

re-q/a-begin:

re-q/a-confirm:

re-q/a-done:

cancel-purchase-begin:

cancel-purchase-confirm:

cancel-purchase-done:

bike-list:

bike-list-by-type:

bike-list-by-area:

model-list-by-brand:

bike-detail:

print-bike-info:

search-history:

favorite-list:
  title: 'bla bla blab bla $h1'
  description: 'this is description total $total and count equal $count'
recently-viewed-products:

q/a-history:

maker-list:

shop-group-detail:

shop-list:
  case1:
    title: 'case1 title test $h1'
    description: 'case1 description total: $total & count: $count'
  case2:
    title: 'case2 title test $h1'
    description: 'case2 description total: $total and count: $count'
shop-detail:

shop-map:

shop-pr-info-list:

shop-pr-info-list:

store-alert-input:

store-alert-confirm:

store-alert-sent:

site-map:

model-summary:

spec-search:

spec-search-form:

compare-model:

model-ranking-favorite:

model-ranking-by-satisfation:

customized-model-ranking:

touring-model-ranking:

category:
